query PageContent($uri: ID!) {
	page(id: $uri, idType: URI) {
		id
		editorBlocks {
			name
			parentClientId
			clientId
			...CoreParagraphFragment
			...CoreHeadingFragment
			...CoreColumnsFragment
			...CoreGroupFragment
			...CoreButtonFragment
			...CoreButtonsFragment
			...CoreSpacerFragment
			...AcfHomeSectionFragment
			...AcfSignupFormFragment
			...AcfHeaderAnimationFragment
		}
		seo {
			...SeoFragment
		}
	}
}

fragment AcfHeaderAnimationFragment on AcfHeaderAnimation {
	apiVersion
	blockEditorCategoryName
	headerAnimation {
		statements {
			statement
			bgcolor
			textcolor
		}
	}
	attributes {
		alignment: align
		backgroundColor
		textColor
	}
}


fragment AcfSignupFormFragment on AcfSignupForm {
  signupForm {
    formId
    emailField
    phoneField
    postcodeField
    unionList
    workplace
  }
  attributes {
    alignment: align
    backgroundColor
    textColor
  }
}

fragment AcfHomeSectionFragment on AcfHomeSection {
	attributes {
		alignment: align
		backgroundColor
		textColor
	}
	innerBlocks {
		name
		parentClientId
		clientId
		...CoreParagraphFragment
		...CoreHeadingFragment
		...CoreColumnsFragment
		...CoreGroupFragment
		...CoreButtonFragment
		...CoreButtonsFragment
		...CoreSpacerFragment
	}
	homeSection {
		accordeonlabel
		defaultActive
	}
}

fragment SeoFragment on PostTypeSEO {
	metaDesc
	metaKeywords
	opengraphSiteName
	opengraphTitle
	opengraphPublisher
	opengraphUrl
	title
	twitterDescription
	twitterTitle
	twitterImage {
		altText
		mediaDetails {
			...MediaDetailsFragment
		}
	}
	opengraphImage {
		altText
		mediaDetails {
			...MediaDetailsFragment
		}
	}
}

fragment MediaDetailsFragment on MediaDetails {
	sizes {
		name
		sourceUrl
		width
		height
	}
}

fragment CoreGroupFragment on CoreGroup {
	attributes {
		backgroundColor
		align
		style
	}
}

fragment CoreButtonFragment on CoreButton {
	attributes {
		backgroundColor
		style
		fontSize
		linkTarget
		text
		url
		className
	}
	innerBlocks {
		apiVersion
		blockEditorCategoryName
		clientId
		name
		parentClientId
		renderedHtml
	}
}

fragment CoreColumnsFragment on CoreColumns {
	attributes {
		layout
		className
		verticalAlignment
		style
		align
	}
}

fragment CoreParagraphFragment on CoreParagraph {
	attributes {
		content
		fontFamily
		fontSize
		textColor
		align
	}
}

fragment CoreHeadingFragment on CoreHeading {
	attributes {
		content
		fontFamily
		fontSize
		textColor
		textAlign
		level
		align
	}
}

fragment CoreSpacerFragment on CoreSpacer {
	attributes {
		height
		style
	}
}

fragment CoreButtonsFragment on CoreButtons {
	attributes {
		align
		layout
		style
		className
		cssClassName
	}
}
